name: Build NSComponent API Application

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - '**'       # main or any specific branch .. for all branch it is '**'
  pull_request:
    branches:
      - main  # Trigger only on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17 (or whichever version of Java you're using)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Maven dependencies for faster builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the project using Maven
      - name: Build with Maven
        run: mvn clean install

      # Optionally run tests
      - name: Run tests
        run: mvn test
